chess:
	mvn install
	mvn exec:java -Dexec.mainClass="search.game.Chess"

tictactoe:
	mvn install
	mvn exec:java -Dexec.mainClass="search.game.TicTacToe"

graph:
	mvn install
	mvn exec:java -Dexec.mainClass="search.graph.GraphDepthFirstSearch"

maze:
	mvn install
	mvn exec:java -Dexec.mainClass="search.maze.MazeBreadthFirstSearch"

