chess:
	mvn install -q
	mvn exec:java -Dexec.mainClass="search.game.Chess" -q

tictactoe:
	mvn install -q
	mvn exec:java -Dexec.mainClass="search.game.TicTacToe" -q

graph:
	mvn install -q
	mvn exec:java -Dexec.mainClass="search.graph.GraphDepthFirstSearch" -q

maze:
	mvn install -q
	mvn exec:java -Dexec.mainClass="search.maze.MazeBreadthFirstSearch" -q


install:
	mvn install -DskipTest -Dmaven.test.skip=true -q
