classifier_wisconsin:
	mvn install
	mvn exec:java -Dexec.mainClass="com.markwatson.deeplearning.ClassifierWisconsinData"

lstm:
	mvn install
	mvn exec:java -Dexec.mainClass="com.markwatson.deeplearning.LstmCharGenerator"

install:
	mvn install -DskipTest -Dmaven.test.skip=true

